### ISSUE TITLE
Use of settings section in connections.yml

### ISSUE THREAD

**Issue by chris-qlik** [qlik-oss/corectl#167]
Not sure if this is my understanding but if I use something like:

```
connections:
  my_conn:
    type: MyConn
    password: mypass
    settings:
      sourceType: MySource
```

When I do a corectl build I get an error:

> Script Error. Internal errors. Means some invariants expected by underlying System has been broken. If you see one of these errors, Something is very broken. (Connector error: Source 'MySourcePassword=mypass' not found.)

I can get it to work by using:

```
connections:
  my_conn:
    type: MyConn;sourceType=MySource
    password: mypass
```

But it seems like the first version should work and is the correct way.
