### ISSUE TITLE
How should user credentials be provided when setting up connections?

### ISSUE THREAD

**Issue by glooms** [qlik-oss/corectl#197]
When setting up a connection to e.g. a database it might look like:
```
mysql:
  connectionstring: ...
  username: user
  password: password
  settings: ...
```
We can apparently not include environment variables in the config file, meaning that sensitive information such as username and password for database connections have to be stated in plain text.

How should this be done?
