### ISSUE TITLE
corectl should honor camelCase YAML

### ISSUE THREAD

**Issue by axelssonHakan** [qlik-oss/corectl#351]
**corectl** is converting the **YAML** to lowercase while creating connections.

If the same naming is used in the load script engine won't find the created connector in the script

---

**corectl.yml**
```
engine: localhost:9076
app: temp.qvf
script: ./script.qvs
connections:
  localHTTPserver:
    connectionstring: http://host.docker.internal:8000/gistemp1200_GHCNv4_ERSSTv5_tempanomaly.csv
    type: internet
```

**traffic**
```
{"jsonrpc":"2.0","delta":false,"method":"CreateConnection","handle":1,"id":4,"params":[{"qName":"localhttpserver","qConnectionString":"http://host.docker.internal:8000/gistemp1200_GHCNv4_ERSSTv5_tempanomaly.csv","qType":"internet"}]}
```

**load script**
```
LOAD
  *
FROM [lib://localHTTPserver]
(txt, utf8, embedded labels, delimiter is ',');
```

**ERROR**
> Script Error. Connection not found: localHTTPserver
