### ISSUE TITLE
Strange parsing in corectl.yml file in connectionstring

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/corectl#483]
When the connectionstring is misspelled in the corectl config file it looks like corectl interpret it as a connectionstring but cuts the string when creating the connection.

As an example 

```yml
engine: localhost:19076
app: happy-thoughts
script: loadscript.qvs
connections:
  jdbc:
    type: jdbc
    username: happybox
    password: keephappiness
    connectring: CUSTOM CONNECT TO "provider=jdbc;driver=mysql;host=thehost;port=3306;database=db"
```

results in a connection with the following properties

```json
{
  "qId": "43532945-4bbd-4701-a843-a7be009ce9df",
  "qName": "jdbc",
  "qConnectionString": "CUSTOM CONNECT TO \"provider=jdbc;\"",
  "qType": "jdbc",
  "qModifiedDate": "1/15/2020 6:44:13 PM",
  "qMeta": {},
  "qLogOn": "LOG_ON_SERVICE_USER"
}
```
