### ISSUE TITLE
Passing a connection via parameters

### ISSUE THREAD

**Issue by carlioth** [qlik-oss/corectl#50]
I would like to be able to create a basic connection via the command line parameter instead of pointing to a file having that information. 
Today: 
`corectl -a app.qvf reload --script ./myscript.qvs --connections ./connectionsyml
`
Change example: 
`corectl -a app.qvf reload --script ./myscript.qvs --connect myconnection:/data
`

Perhaps a key value passed or similar

**Comment by FredrikFolkesson** [comment]
Looking at a connector example
```
connections:
  myconnection:
    type: testconnector
    username: gwe
    settings:
      host: corectl-test-connector
```

How would you pass in "second level" parameters? e.g the host in this case?
